config/routes.rb
Rails.application.routes.draw do
  resources :todo_items do
    collection do
      patch 'clear_completed'
    end
  end

  root 'todo_items#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :find_todo_item, only:[:update, :destroy, :edit]

		def index
			@todo_item = TodoItem.new
			@all_todo_items = TodoItem.all
		  if params[:complete] == "true"
		    @all_todo_items = @all_todo_items.where(complete: true)	
		  elsif params[:complete] == "false"	
		  	@all_todo_items = @all_todo_items.where(complete: false)
		  end	
		end

		def create
			@todo_item = TodoItem.create(todo_item_params)
			redirect_to root_url
		end

		def update
			#@todo_item = TodoItem.find(params[:id])
			@todo_item.update(todo_item_params)
			redirect_to root_url
		end

		def edit
		end

		def destroy
			@todo_item.destroy
			redirect_to root_url
		end

		def clear_completed
			TodoItem.where(complete: true).update_all(complete: false)
			redirect_to root_url
		end
		
		private

		def find_todo_item
			@todo_item = TodoItem.find(params[:id])
		end

		def todo_item_params
			params.require(:todo_item).permit(:name, :complete)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
	<head>
		<title>TwoDoMvc</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/todo_items/edit.html.erb
<h1>Edit Item: <%= @todo_item.name %></h1>

<%= form_for @todo_item do |f| %>
	<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
</p>

<p>
	<%=f.submit %>
</p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/todo_items/index.html.erb
<section id="todoapp">
	<header id="header">
		<h1>todos</h1>
		<%= form_for @todo_item do |f| %>
			<%= f.text_field :name, placeholder: "What needs to be done?", id: "new-todo", autofocus: true %>
			<%= f.submit %>
		<% end %>
	</header>
	<!-- This section should be hidden by default and shown when there are todos -->
	<% if @all_todo_items.count > 0 %>
	<section id="main">
<!-- 		<input id="toggle-all" type="checkbox">
		<label for="toggle-all">Mark all as complete</label> 
 -->		
		<ul id="todo-list">
			<% @all_todo_items.each do |item| %>
			<!-- List items should get the class `editing` when editing and `completed` when marked as completed -->
			<li <% 'class=completed' if item.complete %>>
				<div class="view">

					<%= form_for item do |f| %>
						<%= f.check_box :complete, class: "toggle" %>
							<%= f.submit "Complete" %>
						<% end %>

						<label><%= item.name %></label>
						<%= link_to 'Edit', edit_todo_item_path(item) %>
					<button class="destroy"></button>
					<%= button_to 'X', item, method: :delete, class: 'destroy' %>
				</div>

			</li>
			<% end %>
		</ul>
	</section>
	<% end %>
	<!-- This footer should hidden by default and shown when there are todos -->
	<footer id="footer">
		<span id="todo-count">
			<strong><%= pluralize@all_todo_items.where(complete: false).count, 'item' %></strong>  left</span>
			

		<!-- Remove this if you don't implement routing -->
		<ul id="filters">
			<li>
				<%= link_to 'All', root_path, class: ('selected' if params[:complete] == nil)%>
			</li>
			<li>
				<%= link_to 'Active', root_path(complete: false), class:('selected' if params[:complete] == false)%>
			</li>
			<li>
				<%= link_to 'Completed', root_path(complete: true), class:('selected' if params[:complete] == true)%>
			</li>
		</ul>
			<% unless @all_todo_items.where(complete: true).count==0%>
			 <button id="clear-completed"></button>
	</footer>
<% end %>
</section>
<footer id="info">
	<p>Double-click to edit a todo</p>
	<!-- Remove the below line ↓ -->
	<p>Template by <a href="http://sindresorhus.com">Sindre Sorhus</a></p>
	<!-- Change this out with your name and url ↓ -->
	<p>Created by <a href="http://todomvc.com">you</a></p>
	<p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
</footer>